version: "3.3"
services:
  apiventa:
    build: ./
    ports:
      - "9000:80"
    environment:
      SERVER: "sqlserver"
      PORT: 1433
      DATABASE: "AppVentaDb"
      USERNAME: "sa"
      PASSWORD: "Channel321*"
      INTEGRATED_SECURITY: "false"
      TRUST_SERVER_CERTIFICATE: "true"
    depends_on:
      - database
    links:
      - "database"
  sql_desarrollo:
    image: "mcr.microsoft.com/mssql/server"
    hostname: "sqlserver_desarrollo"
    environment:
      SA_PASSWORD: "Channel321*"
      ACCEPT_EULA: "Y"
    volumes:
      - desarrollo_data:/var/opt/mssql/data
  sql_qa:
      image: "mcr.microsoft.com/mssql/server"
      hostname: "sqlserver_qa"
      environment:
        SA_PASSWORD: "Channel321*"
        ACCEPT_EULA: "Y"
      volumes:
        - qa_data:/var/opt/mssql/data
  sql_produccion:
      image: "mcr.microsoft.com/mssql/server"
      hostname: "sqlserver_produccion"
      environment:
        SA_PASSWORD: "Channel321*"
        ACCEPT_EULA: "Y"
      volumes:
        - facturacionData:/var/opt/mssql/data

volumes:
  facturacionData:
  qa_data:
  desarrollo_data: